#Upset plot
install.packages("ComplexUpset")
install.packages("ggplot2")
install.packages("ggplot2movies")
install.packages("ggbreak")


library(ComplexUpset)
library(ggplot2movies)
library(ggplot2)
library(ggbreak) 
library(dplyr)

#assigning the upset ComplexUpset::upset function to upset_complex
upset_complex <-  ComplexUpset::upset

#setting current dir
setwd('/Users/gfrosi/scratch/compared_dbs_2023_final/')

#loading the Histones_DBs_ENCODE_upset generated by input_upset.py
test <- read.csv('Histones_basedDBs_57566_2023_08_03_consensus_ENCODE_upset_ENCODEgroup.csv')

#checking col names
colnames(test) 

#getting GSM + DBs + groups (Hist_Inp or Other) columns
test_select <- test %>% select(c("GSM","GEO","NGSQC","CA","CistromeDB","ENCODE","groups_ENCODE"))

#DBs categories
col <- colnames(test_select)[2:5] 
col


#just the upset plot 
DBupset <- upset_complex(
  test,
  col,
  name='Public Dabases',
  width_ratio=0.1,
  set_sizes=(upset_set_size() + theme(axis.text.x=element_text(angle=90))),
  base_annotations=list(
    'Intersection size'=intersection_size(
      text=list(vjust=-0.1,
                hjust=-0.1,
                angle=90,
                size=3),
      text_colors =c(on_backgound ='black', on_bar='black'),
      counts=TRUE,
      mapping=aes(fill=groups)))) + 
      ggtitle('Samples (GSM) in 4 Dbs') +
      theme(plot.title = element_text(hjust = 0.5))

DBupset
ggsave("upset_test.png", DBupset ,dpi=300)


#upset plus percentages
DBupsetPerc <- upset_complex(
  test,
  col,
  name='Public Dabases',
  width_ratio=0.1,
  set_sizes=(upset_set_size() + theme(axis.text.x=element_text(angle=90))),
  annotations = list(
    'ENCODE Rating'=(
      ggplot(mapping=aes(fill=groups_ENCODE))
      + geom_bar(stat='count', position='fill')
      + scale_y_continuous(labels=scales::percent_format())
      + ylab('ENCODE Rating'))),
  base_annotations=list(
    'Intersection size'=intersection_size(
    text=list(vjust=-0.1,
    hjust=-0.1,
    angle=24,
    size=3),
    text_colors =c(on_backgound ='black', on_bar='black')
  )))

ggsave("upset_DBs_percentages_ENCODE.png", DBupsetPerc ,dpi=300)
